Fix border bleed on fieldsets
canonical-web-and-design/cn.ubuntu.com pull request #463
Opened 2020-11-24 14:42 UTC by pmahnke

## Done

- fix border bleed [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/3424) by adding `border-color:#cdcdcd;` to the fieldsets

## QA

1. Download this branch and run it.
2. compare http://0.0.0.0:8010/engage/ubuntu-tech-live-episode-3 with https://cn.ubuntu.com/engage/ubuntu-tech-live-episode-3

## Screenshots

[live]
![image](https://user-images.githubusercontent.com/441217/100108935-3f165400-2e63-11eb-8a50-ebeb0e5adfc1.png)

[this branch]
![image](https://user-images.githubusercontent.com/441217/100108999-4ccbd980-2e63-11eb-8405-badbaff134e6.png)

2020-11-24 14:43 UTC, webteam-app commented
Demo starting at https://cn-ubuntu-com-463.demos.haus

2020-11-24 14:52 UTC, zprood commented
@pmahnke Thanks, it's working now.

2020-11-24 20:00 UTC, anthonydillon requested changes
Why not apply it to the CSS and add a comment containing a link to the issue. Would make it easier to remove one fixed.

2020-11-24 21:11 UTC, pmahnke commented
@anthonydillon it already had a bunch of styles **and** it will be removed for the discourse solution soon.

2020-11-25 11:55 UTC, anthonydillon approved these changes
Ok :+1:

2020-11-25 11:55 UTC, merged