Add secondary nav and new /internet-of-things/core page
canonical-web-and-design/cn.ubuntu.com pull request #496
Opened 2021-03-05 12:02 UTC by bethcollins92

## Done

- Add secondary nav for IoT section
- Add new core page at `/internet-of-things/core` - refactored this [branch](https://github.com/zprood/cn.ubuntu.com/blob/master/templates/core/index.html) as the page wasn't responsive and the headings weren't ordered correctly. Also extracted the styles from the html file and injected them into scss files.

## QA

- Visit page at: 
- Check secondary nav for IoT - described [here](https://github.com/canonical-web-and-design/web-squad/issues/3890)
- `/internet-of-things/core page` content should match ubuntu.com/core - copy [here](https://github.com/zprood/cn.ubuntu.com/blob/master/templates/core/index.html)

## Issue / Card

[#3890](https://github.com/canonical-web-and-design/web-squad/issues/3890)

## Screenshots

![image](https://user-images.githubusercontent.com/58959073/110113103-85584900-7daa-11eb-9156-f1c721bd3b30.png)

2021-03-05 12:02 UTC, webteam-app commented
Demo starting at https://cn-ubuntu-com-496.demos.haus

2021-03-05 12:40 UTC, zprood commented
@bethcollins92 Thank you, I notice that there is a problem on the /core page with the second and third section if resizing the page towards the horizontal direction. It's working with 1080p resolution and lower but broken over 1080P, like 2K, 3K, 4K. 
![image](https://user-images.githubusercontent.com/692206/110115770-86f92f80-7df1-11eb-9f55-bb945d2d7f9b.png)

2021-03-05 12:45 UTC, bethcollins92 commented
@zprood ah I'll take a look, thanks!

2021-03-05 12:45 UTC, anthonydillon requested changes
Looks good with a few comment in the code

2021-03-05 12:45 UTC, anthonydillon commented on static/sass/_pattern_core.scss
> +    .p-banner-core-hero {
Doesn't look like this is used

2021-03-05 12:45 UTC, anthonydillon commented on templates/internet-of-things/core.html
> +    <div class="row u-vertically-center u-align--center">
The `u-align--center` here is stoping the row doing its thing. Can you add a `col-12` div inside with the align class

2021-03-05 12:45 UTC, anthonydillon commented on templates/internet-of-things/core.html
> +    <div class="row u-equal-height u-align--center u-vertically-center u-hide--small">
Again we should align at the column level.

2021-03-05 12:45 UTC, anthonydillon commented on templates/internet-of-things/core.html
> +    <div class="row u-align--center">
Here too

2021-03-05 12:45 UTC, anthonydillon commented on templates/internet-of-things/core.html
> +    <div class="row u-equal-height u-align--center u-vertically-center u-hide--small">
And here

2021-03-05 12:45 UTC, anthonydillon commented on templates/internet-of-things/core.html
> +    <div class="row u-align--center">
And here

2021-03-05 12:45 UTC, anthonydillon commented on templates/internet-of-things/core.html
> +          <a href="https://ubuntu.com/core/features/secure-boot">了解更多关于安全启动的内容&nbsp;&rsaquo;</a>
This should be an external link

2021-03-05 12:45 UTC, anthonydillon commented on templates/internet-of-things/core.html
> +          <a href="https://ubuntu.com/core/features/full-disk-encryption">了解更多关于全盘加密的内容&nbsp;&rsaquo;</a>
Same here

2021-03-05 12:45 UTC, anthonydillon commented on templates/internet-of-things/core.html
> +      <h2>通过SMART START快速进入市场</h2>
Can you put these in a column please

2021-03-05 12:56 UTC, bethcollins92 commented
Thanks @anthonydillon, applied those fixes 👍🏼

2021-03-05 13:27 UTC, zprood commented
@bethcollins92 @anthonydillon Thank you. Sorry for missing the URL and just update the last button link address.

2021-03-08 14:03 UTC, anthonydillon approved these changes
Sorry for the delay. LGTM :+1:

2021-03-08 14:10 UTC, carkod commented
I just merged some PRs and deployed to prod @bethcollins92  can you rebase? Thanks

2021-03-08 15:04 UTC, merged